jobs:
  deploy:
    # Memanggil runner 'rifki' menggunakan kombinasi labelnya
    runs-on: [self-hosted, Linux, X64]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Uji coba koneksi
        run: echo "Workflow ini berhasil berjalan di server Debian Rifki!"