name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    # Ubah bagian ini untuk menargetkan server Anda
    runs-on: self-hosted 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Uji coba runner
        run: echo "Proses ini berjalan di server Debian saya!"