name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    # Mengarahkan job ini ke self-hosted runner Anda
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Test Runner
        run: echo "Hello dari server Debian saya!"